# Generated by Django 3.1.4 on 2021-02-18 09:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_userpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('location', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.AlterModelOptions(
            name='worldcities',
            options={'ordering': ('accentcity',)},
        ),
    ]
