# Generated by Django 3.1.4 on 2020-12-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
