# Generated by Django 3.1.4 on 2021-01-29 07:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20201230_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('articleContent', models.TextField()),
                ('status', models.CharField(choices=[('wait', 'Wait'), ('ready', 'Ready')], default='wait', max_length=10)),
            ],
            managers=[
                ('ready', django.db.models.manager.Manager()),
            ],
        ),
    ]
