# Generated by Django 3.1.4 on 2021-01-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('details', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('project_url', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
