# Generated by Django 3.1.4 on 2021-02-24 04:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatialdemos', '0003_auto_20210223_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='KenyaCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.AlterModelOptions(
            name='storecustomer',
            options={'ordering': ['name']},
        ),
    ]
