# Generated by Django 3.1.4 on 2021-02-24 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatialdemos', '0004_auto_20210224_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kenyacounty',
            options={'ordering': ['name']},
        ),
    ]
