# Generated by Django 3.1.4 on 2021-02-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatialdemos', '0005_auto_20210224_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampledIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=250)),
                ('counties', models.ManyToManyField(to='spatialdemos.KenyaCounty', verbose_name='list of counties')),
            ],
        ),
    ]
