# Generated by Django 3.1.4 on 2021-02-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatialdemos', '0006_sampledissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampledissue',
            name='counties',
            field=models.ManyToManyField(related_name='counties', to='spatialdemos.KenyaCounty', verbose_name='list of counties'),
        ),
    ]
